//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by A-Protect.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MYAProtect_FORM             101
#define ID_Exit                         102
#define ID_OpenKernelType               103
#define ID_ShutdownKernelType           104
#define ID_ProtectProcess               105
#define ID_UnProtectProcess             106
#define ID_Booting                      107
#define ID_CancelBooting                108
#define ID_WindowsOverhead              109
#define ID_CancelTheOverhead            110
#define ID_About                        111
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MyAProtectTYPE              130
#define IDM_MATREP_DELETEDATE           141
#define IDS_EDIT_MENU                   307
#define IDR_SSDT_MENU                   308
#define IDR_MENU1                       309
#define IDR_SHADOWSSDT_MENU             310
#define IDI_ICON1                       311
#define IDI_ICON2                       312
#define IDI_ICON3                       313
#define IDI_ICON4                       314
#define IDI_ICON5                       315
#define IDI_ICON6                       316
#define IDI_ICON7                       317
#define IDI_ICON8                       318
#define IDI_ICON9                       319
#define IDI_ICON13                      320
#define IDB_BITMAP1                     321
#define IDB_SPLASH                      322
#define IDR_KERNELHOOK_MENU             323
#define IDD_DLG_PROMODULE               324
#define IDR_KERNELMODULE_MENU           325
#define IDD_DLG_PROCESSSEARCH           326
#define IDR_KERNELTHREAD_MENU           327
#define IDI_ICON10                      328
#define IDD_DIALOG3                     328
#define IDD_DLG_STACKTHREAD             328
#define IDI_WHITE                       329
#define IDD_DLG_KERNALDATA              329
#define IDR_SYSTEMTHREAD_MENU           330
#define IDD_DIALOG4                     330
#define IDD_DLG_SKMHOOK                 330
#define IDI_ICON11                      331
#define IDD_DLG_SELECTANYMODELE         331
#define IDR_FILTERDRIVER_MENU           332
#define IDD_DIALOG1                     333
#define IDI_ICON14                      333
#define IDD_DLG_SNIFFERSETTING          334
#define IDI_ICON15                      334
#define IDR_FSDHOOK_MENU                335
#define IDD_DIALOG2                     336
#define IDD_PROTECTSETTING              337
#define IDR_TCPIPHOOK_MENU              338
#define IDR_NSIPHOOK_MENU               339
#define IDR_TCPVIEW_MENU                340
#define IDR_HIPSLOG_MENU                341
#define IDR_SERVICES_MENU               342
#define IDR_PROCESS_MENU                343
#define IDI_ICON16                      343
#define IDR_DLLMODULE_MENU              344
#define IDI_ICON17                      344
#define IDC_TREE1                       345
#define IDC_LIST2                       346
#define IDC_DebugStatus                 347
#define ID_SSDTHook                     348
#define IDC_OpenURL                     349
#define ID_SSDTAllHook                  350
#define IDI_ICON18                      350
#define IDC_LIST1                       351
#define IDI_ICON19                      351
#define IDC_InterNetInfo                352
#define IDC_BUTTON1                     353
#define ID_OK                           353
#define IDC_BTN_SCAN                    353
#define IDC_BTN_CLOSE                   354
#define IDI_ICON20                      354
#define ID_UnHookSSDTHookSelect         355
#define IDI_ICON21                      355
#define IDC_DeleteFile                  356
#define IDI_ICON22                      356
#define ID_UnHookSSDTHookAll            357
#define IDI_ICON23                      357
#define IDC_DisLoadDriver               358
#define IDI_ICON24                      358
#define ID_CopySSDTDataToClipboard      359
#define IDI_ICON25                      359
#define IDC_DisCreateProcess            360
#define IDI_ICON26                      360
#define ID_ShadowSSDTHook               361
#define IDC_DisCreateFile               362
#define ID_ShadowSSDTAllHook            363
#define IDC_DisSrvReset                 364
#define IDI_ICON28                      364
#define ID_UnHookShadowSSDTHookSelect   365
#define IDC_DisKernelThread             366
#define IDI_ICON30                      366
#define ID_UnHookShadowSSDTHookAll      367
#define IDC_ShutdownSystem              368
#define ID_CopyShadowSSDTDataToClipboard 369
#define IDC_BUTTON9                     370
#define IDI_ICON34                      370
#define IDR_KBDCLASSHOOK_MENU           371
#define IDR_MOUCLASSHOOK_MENU           372
#define IDR_ATAPIHOOK_MENU              373
#define IDR_DPCTIMER_MENU               374
#define IDR_SYSTEMNOTIFY_MENU           375
#define IDR_PROCESSTHREAD_MENU          376
#define IDI_ICON12                      378
#define IDI_ICON40                      379
#define IDI_ICON45                      384
#define IDI_ICON48                      390
#define IDI_ICON49                      392
#define IDI_ICON50                      396
#define IDI_ICON51                      398
#define IDM_MATREP_EXPORT               800
#define IDC_Uninstall360                1015
#define ID_KernelHook                   1016
#define IDC_EDIT1                       1017
#define ID_UnHookKernelHookSelect       1018
#define IDC_EDIT3                       1018
#define IDC_EDIT_SHOWKERNELDATA         1018
#define IDC_EDIT2                       1019
#define IDC_EDIT_FIND                   1020
#define IDC_SearchStatus                1020
#define IDC_EDIT_FINDINFO               1021
#define IDC_COMBO1                      1021
#define IDC_COMBO_KERNELBASE            1021
#define ID_ByPassKernelHook             1022
#define IDC_EDIT_LOOKUPSIZE             1022
#define IDC_STATIC_TITLE                1023
#define ID_BTNOK                        1023
#define ID_CopyKernelHookDataToClipboard 1024
#define IDC_LIST_SELECTANYMODULE        1024
#define ID_BTN_SEARCH                   1025
#define IDC_BUTTON2                     1025
#define IDC_BTN_SELECTALL               1025
#define ID_SystemThreadList             1026
#define ID_BTN_SEARCH2                  1026
#define ID_STOP_SEARCH                  1026
#define IDC_BTN_CANCELSELECT            1026
#define ID_SuspendSelectThread          1027
#define ID_ResumeSelectThread           1028
#define ID_KillSelectThread             1029
#define ID_FilterDriverList             1030
#define ID_DeleteSelectFilterDriver     1031
#define ID_FsdHookList                  1032
#define ID_FsdHookResetOne              1033
#define ID_CopyFsdDataToClipboard       1034
#define ID_TcpipHookList                1035
#define ID_TcpipHookResetOne            1036
#define ID_CopyTcpipDataToClipboard     1037
#define ID_NsipHookList                 1038
#define ID_NsipHookResetOne             1039
#define ID_CopyNsipDataToClipboard      1040
#define ID_Tcpview                      1041
#define ID_KillTcpProcess               1042
#define ID_HipsLog                      1043
#define ID_ConnectScan                  1044
#define ID_SaveToFile                   1045
#define ID_ClearListLog                 1046
#define ID_GetServicesList              1047
#define ID_RestartToGetServicesList     1048
#define ID_StartServices                1049
#define ID_StopServices                 1050
#define ID_ManualServices               1051
#define ID_AutoServices                 1052
#define ID_DisableServices              1053
#define ID_DeleteServices               1054
#define ID_Process                      1055
#define ID_ProcessModule                1056
#define ID_KillProcess                  1057
#define ID_KillProcessDeleteFile        1058
#define ID_ProcessVerify                1059
#define ID_CopyProcessDataToClipboard   1060
#define ID_UnLoadDLLModule              1061
#define ID_UnLoadDLLModuleAndDeleteFile 1062
#define ID_LookupDLLInServices          1063
#define ID_CopyDLLDataToClipboard       1064
#define ID_KbdclassHookList             1065
#define ID_KbdclassHookResetOne         1066
#define ID_CopyKbdclassDataToClipboard  1067
#define ID_MouclassHookList             1068
#define ID_MouclassHookResetOne         1069
#define ID_CopyMouclassDataToClipboard  1070
#define ID_AtapiHookList                1071
#define ID_AtapiHookResetOne            1072
#define ID_CopyAtapiDataToClipboard     1073
#define ID_DpcTimerList                 1074
#define ID_KillDpcTimer                 1075
#define ID_CopyDpcTimerDataToClipboard  1076
#define ID_SystemNotifyList             1077
#define ID_KillSystemNotify             1078
#define ID_CopySystemNotifyDataToClipboard 1079
#define IDC_DllDebugStatus              1080
#define ID_ProcessHandle                1081
#define ID_ProcessThread                1082
#define ID_ProcessThreadList            1083
#define ID_SuspendSelectProcessThread   1084
#define ID_ResumeSelectProcessThread    1085
#define ID_KillSelectProcessThread      1086
#define ID_QueryAllProcessModule        1088
#define ID_DLLModuleWithOutTrust        1089
#define ID_TrustProcFile                1090
#define IDR_TCPSNIFFER_MENU             1091
#define ID_SnifferTcpSetting            1092
#define ID_KernelModule                 1093
#define ID_KernelModule1                1094
#define ID_DumpMemoryDataToFile         1095
#define ID_CopyKernelModuleDataToClipboard 1096
#define ID_KernelThreadList             1097
#define ID_ClearKernelThreadLog         1098
#define ID_TrustDllFile                 1099
#define ID_KernelModuleTrust            1100
#define ID_ProcessTrust                 1101
#define ID_ProcessModuleTrust           1102
#define ID_GetServicesListByTrust       1103
#define IDR_WORK_QUEUE_MENU             1104
#define ID_WrokQueue                    1105
#define ID_KillWrokQueue                1106
#define ID_SuspendWrokQueue             1107
#define ID_ResumeWrokQueue              1108
#define ID_SystemThreadStack            1109
#define ID_SuspendSelectProcess         1110
#define ID_ResumeSelectProcess          1111
#define ID_SearchProcessWithGoogle      1112
#define ID_GetProcessFilePath           1113
#define ID_QueryProcessIAT              1114
#define ID_OpenSrcDownLoad              1115
#define ID_DDCommand                    1116
#define ID_OpenUrl                      1117
#define ID_BSOD                         1118
#define ID_SelectModuleInlineHook       1119
#define ID_AllKernelHook                1120
#define ID_CopyProcessMD5ToClipboard    1121
#define IDC_ReadPDB                     1122
#define IDC_StackDebug                  1123
#define IDC_DisUserHook                 1124
#define IDR_IOTIMER_MENU                1125
#define IDC_DisUserHook2                1125
#define IDC_DisDllFuck                  1125
#define ID_IoTimerList                  1126
#define ID_StopIoTimer                  1127
#define ID_StartIoTimer                 1128
#define ID_CopyIoTimerDataToClipboard   1129
#define IDR_EYE_MENU                    1130
#define ID_EyePC                        1131
#define ID_EyeBIN                       1132
#define ID_EyeLookLog                   1133
#define ID_StopHookScan                 1134
#define ID_StartOnly                    1135
#define ID_UnTrustOnly                  1136
#define ID_GetPDB                       1137
#define IDR_MESSAGE_HOOK_MENU           1138
#define ID_MessageHookFunction          1139

#define ID_OPTIONS_32777                32777
#define ID_OPTIONS_32780                32780
#define ID_OPTIONS_32782                32781
#define ID_OPTIONS_32783                32783
#define IDM_SSMODULE                    32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        400
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
